# Generated by Django 3.1.2 on 2020-10-30 14:53

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_video',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='timer_last_active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 20, 23, 39, 948257)),
        ),
    ]
